[FE] Fix: Alert arr 해결
codestates-seb/seb45_main_031 pull request #160
Opened 2023-09-16 14:53 UTC by jooy45

- 입력칸을 모두 입력하지 않은 상태에서 확인을 눌렀을 시 알럿이 뜨지 않는다.
- 비밀번호와 컨펌이 다르게 확인을 눌러도 알럿이 뜨지 않고 회원가입이 된다.
- 취소 버튼을 눌렀을 시 로그인 화면으로 돌아가지 않는다.

#159

2023-09-17 11:31 UTC, kimmand0o0 requested changes

2023-09-18 08:50 UTC, closed without merging

2023-09-18 08:53 UTC, jooy45 commented on FE/src/pages/SignUpPage.js
> +  }
disabled 속성을 넣으면 사용자에게 에러 Alert을 보여주지 못해서 고민중이었습니다 ㅠ 조금 생각후 변경하겠습니다 !

2023-09-18 08:53 UTC, jooy45 commented on FE/src/pages/SignUpPage.js
>    };
확인입니다 !

2023-09-18 08:53 UTC, jooy45 commented on FE/src/pages/SignUpPage.js
> +      alert("회원가입이 성공적으로 완료되었습니다.");
확인입니다 !